<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RaihanPC" failures="0" tests="4" name="hw_20.Use_of_expected_exception" time="30.254" errors="0" timestamp="2022-04-07T14:46:20 EDT" skipped="2">
  <testcase classname="hw_20.Use_of_expected_exception" name="searchButton" time="10.119"/>
  <system-out/>
  <testcase classname="hw_20.Use_of_expected_exception" name="searchButton" time="20.135"/>
  <system-out/>
  <testcase classname="hw_20.Use_of_expected_exception" name="testWithExpectedException">
    <skipped/>
  </testcase> <!-- testWithExpectedException -->
  <system-out/>
  <testcase classname="hw_20.Use_of_expected_exception" name="expectedExcetionTest">
    <skipped/>
  </testcase> <!-- expectedExcetionTest -->
  <system-out/>
</testsuite> <!-- hw_20.Use_of_expected_exception -->
